version: '3.8'

services:

  bridge:
    image: 127.0.0.1:5000/smarthome/bridge:latest
    hostname: navi.fritz.box
    networks:
      - host
    volumes:
      - 'bridge_data:/app/data'

volumes:

  bridge_data:

networks:

  host:
    external: true
