version: '3.8'

services:

  registry:
    image: registry:2.7.1
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - 'registry_data:/var/lib/registry'
    ports:
      - '5000:5000'

volumes:

  registry_data:
