global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: temperature
    scrape_interval: 5m
    static_configs:
      - targets: ['temperature:8080']

  - job_name: wttr_in_mering
    scrape_interval: 15m
    static_configs:
      - targets: ['wttr.in']
        metrics_path: '/Mering'
        params:
          format: ['p1']
